# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ad3fe0a40528812fa5c3b82a43dddc9764ee9ac006f2a58cc8f14f6dd34ace186a0fa259a321bda5af014edf5a18ce9108cf5a8719adcc307ba98fe2ab35f92

test:
  secret_key_base: 18e915ce19c91f31e9d13f3b8f5ec7165381b264ff18535f5ff2b82c10d03557bed31427018856aa7dae32a39ec495af3cbe99f25e437add0fb99d27391f19a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
